export const ages = [
    "All",
    "2 Y",
    "2.5 - 3 Y",
    "3 Y",
    "3 - 3.5 Y",
    "3.5 Y",
    "3.5 - 4 Y",
    "4 Y",
    "5 Y",
    "5 - 5.5 Y",
    "5.5 Y",
    "5.5 - 6 Y",
    "6 Y"
];

export const titles = [
    { name: "Age", color: 'blue' },
    { name: "Practical Life", color: 'blue' },
    { name: "Sensorial", color: 'blue' },
    { name: "Language", color: 'blue' },
    { name: "Mathematics", color: 'blue' },
    { name: "Culture", color: 'blue' }
]

export const ageWiseData = [
    {
        age: "2.5 Y",
        data1: ["Screwing and unscrewing lids", " folding clothes", "pouring grains 1 to 1", "pouring grains 1 to 2", "pouring grains 1 to 3 equale", "pouring grains 1 to 3 unequal", "liquid pouring 1 to 1", "pouring liquid 1 to 2", "pouring liquid 1 to 3 equal", "pouring liquid 1 to 3 unequal"],
        data2: [],
        data3: ["classified pictures", "sound game", "Question Game", "News Period", "Parts of speech games"],
        data4: [],
        data5: [],
    },
    {
        age: "2.5 - 3 Y",
        data1: ["Press button", "hook and eye", "Large button", "Small button"],
        data2: ["cylinder blocks", "Touch boards",],
        data3: [],
        data4: [],
        data5: [],
    },
    {
        age: "3 Y",
        data1: ["Braiding 1", "Braiding 2", "Braiding 3", "Braiding 4", "Brass polishing", "Glass polishing", "Sweeping Mopping"],
        data2: ["Pink Tower", "Brown Stairs", "Colour Tablets box 1", "Colour Tablets box 2", "Colour tablets box 3", "Touch Tablets"],
        data3: [],
        data4: [],
        data5: [],
    },
    {
        age: "3 - 3.5 Y",
        data1: ["Washing Hands", "Washing clothes"],
        data2: ["Stereognostic Bag 1", "Sterognostic Bag 2", "Stereognostic Bag 3", "Stereognostic Bag 4"],
        data3: [],
        data4: [],
        data5: [],
    },
    {
        age: "3.5 Y",
        data1: ["Flower Arrangement", "Bells"],
        data2: [ "Red Rods", "Geometric Cabinets", "Geometric Cabinets and cards", "Fabrics Box", "Thermic Tablets", "Baric Tablets", "Stereognostic Tray", "Tasting bottles", "Smelling Bottles", "Sound Boxes"],
        data3: ["Sandpaper Letters"],
        data4: [],
        data5: ["Sandpaper Globe", "Coloured Globe", "Land and Water forms", "Puzzle Maps", "Picture folders"],
    },
    {
        age: "3.5 - 4 Y",
        data1: [],
        data2: ["Geometric Solids"],
        data3: [],
        data4: [],
        data5: [],
    },
    {
        age: "4 Y",
        data1: [],
        data2: ["Decanomial Square", "Binomial Cube", "Trinomial Cube", "Constructive Triangles box 1",  "Constructive Triangles box 2", "Thermic Tablets", "Mystery Bag"],
        data3: ["Moveable Alphabets", "Metal Insets", "Object Box 1", "Object Box 2"],
        data4: ["Number Rods", "Sandpaper Numerals", "Number Rods and Cards", "Spindle Box", "Cards and Counters", "Memory Game"],
        data5: ["Flags and Pin maps", "Roman Arch"],
    },
    {
        age: "4 - 4.5 Y",
        data1: ["Bow Frame", "Lace Frame"],
        data2: ["Constructive Triangles box 3",  "Constructive Triangles box 4","Constructive Triangles box 5",  "Constructive Triangles box 6", "Graded Figures"],
        data3: ["Action Cards"],
        data4: [],
        data5: [],
    },
    {
        age: "4.5 Y",
        data1: [],
        data2: ["Knobless Cylinders"],
        data3: ["Puzzle Words", "Reading Folders", "Environmental Cards", "Classified Reading"],
        data4: ["Decimal System", "Addition Multiplication Subtraction Division", "Stamp Game Addition Multiplication Subtraction Division", "Teen beads", "Teen boards", "Teen Beads and Board", "Tens Beads and Boards", "Linear Counting", "Skip Counting", "Fractions", "Fractions Addition Multiplication Substraction Division"],       
        data5: [],
    },
    {
        age: "5 Y",
        data1: [],
        data2: [],
        data3: ["Capitals", "Punctuation", "Definition Stages", "Article", "Adjective", "Logical Adjective", "Detective Adjective", "Conjunction", "Preposition"],
        data4: ["Dot Game", "Addition Snake Game", "Addition Strip Board", "Subtraction Snake Game", "Subtraction Strip Board"],       
        data5: [],
    },
    {
     age: "5 - 5.5 Y",
        data1: [],
        data2: [],
        data3: [],
        data4: ["Addition Chart 1", "Addition Chart 2", "Addition Chart 3", "Addition Blank Chart"],
        data5: [],
    },
     {
        age: "5.5 Y",
        data1: [],
        data2: [],
        data3: ["Written Question Game", "Verb", "Adverb", "Logical Adverb", "Continuation of commands", "Word Study- Synonyms", "Word Study- Homophones", "Word Study- Gender", "Word Study- Compound Words", "Word Study- Numbers", "Word Study- Word Families", "Word Study- Prefix", "Word Study- Suffix"],
        data4: ["Multiplication Bead Bar", "Multiplication Chart 1","Multiplication Chart 2", "Multiplication Chart 3", "Unit Division Board", "Short Bead Frame- Addition Subtraction Multiplication Division", "Hierarchies"],
        data5: [],
    },
 {
     age: "5.5 - 6 Y",
        data1: [],
        data2: [],
        data3: [],
        data4: ["Subtraction Chart 1", "Subtraction Chart 2", "Division Chart 1", "Division Chart 2"],
        data5: [],
    },
      {
        age: "6 Y",
        data1: [],
        data2: [],
        data3: ["Reading Analysis"],
        data4: ["Long Bead Frame", "Long Bead Frame Addition Multiplication Subtraction", "Division with Rack and Tubes"],      
        data5: [],
    },
];


